# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Proj\计算概论\大作业\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow,label):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1500, 1360)
        mainWindow.setMinimumSize(QtCore.QSize(1500, 1360))
        mainWindow.setMaximumSize(QtCore.QSize(1500, 1360))
        mainWindow.setAccessibleDescription("")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setAccessibleDescription("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Show_label = label(self.centralwidget)
        self.Show_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Show_label.sizePolicy().hasHeightForWidth())
        self.Show_label.setSizePolicy(sizePolicy)
        self.Show_label.setMinimumSize(QtCore.QSize(1300, 1300))
        self.Show_label.setMaximumSize(QtCore.QSize(1300, 1300))
        self.Show_label.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.Show_label.setMouseTracking(True)
        self.Show_label.setTabletTracking(False)
        self.Show_label.setAccessibleDescription("")
        self.Show_label.setText("")
        self.Show_label.setObjectName("Show_label")
        self.horizontalLayout.addWidget(self.Show_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.stbutton = QtWidgets.QPushButton(self.centralwidget)
        self.stbutton.setAccessibleDescription("")
        self.stbutton.setObjectName("stbutton")
        self.verticalLayout.addWidget(self.stbutton)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.log = QtWidgets.QTextBrowser(self.centralwidget)
        self.log.setAccessibleDescription("")
        self.log.setObjectName("log")
        self.verticalLayout.addWidget(self.log)
        self.horizontalLayout.addLayout(self.verticalLayout)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setAccessibleDescription("")
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.pushButton.clicked.connect(mainWindow.ai_start) # type: ignore
        self.stbutton.clicked.connect(mainWindow.pvp_start) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "五子棋-李佳霖2231313815"))
        self.stbutton.setText(_translate("mainWindow", "双人对战"))
        self.pushButton.setText(_translate("mainWindow", "人机对战"))
        self.log.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
